### PR TITLE
update version python

### PR DESCRIPTION
**Pull request by hanne-opseth-rygg-4ss**
## Description
Update python versions

### CODE REVIEW

**Review by heidi-holm-4ss — CHANGES_REQUESTED** [review]
you also need to update the documentation about which versions we are supporting.
have you done some actual testing that yourselves that it works with python 3.11 or jsut updated the workflow yml files?

**Comment by hanne-opseth-rygg-4ss** [comment]
I have just updated the yml-files, I have just assumed that if the github actions went through then it would work correctly, but that's maybe a wrong assumption @heidi-holm-4ss

**Comment by heidi-holm-4ss** [comment]
I suggest you create an environment with python 3.11 and verifies that the tests work and that you are able to authenticate and download data

**Comment by hanne-opseth-rygg-4ss** [comment]
@heidi-holm-4ss 

I have now run the application with python version 3.11.0. All the tests works.

**Review by heidi-holm-4ss — APPROVED** [review]

**Pull request merged**
