### PR TITLE
Enhance retry on requests towards Azure Blob Storage

### PR DESCRIPTION
**Pull request by ivan-nikalaichanka-4ss**
## Description
Enhanced the existing retry policies against Azure Blob Storage with delays between attempts.
Increased the connection timeout for HTTP requests against Azure Blob Storage.

### CODE REVIEW

**Review by bjorn-einar-bjartnes-4ss — APPROVED** [review]

**Comment by bjorn-einar-bjartnes-4ss** [comment]
We should look at commit message style

**Comment by ivan-nikalaichanka-4ss** [comment]
> We should look at commit message style Code looks fine but @heidi-holm-4ss mentioned commit guidelines.

I'd suggest "ENH: enforce retry on azure requests with delays between attempts, and change timeout" when merging the PR into the `master` branch.

**Comment by bjorn-einar-bjartnes-4ss** [comment]
Not entirely sure yet on what ends up in the release notes automatically and what we can rewrite, but it could be good to say something about the intention.
"think of the commit message as describing the problem that has been solved/what feature has been added, rather than how that change has been implemented. "

ENH: Downloading timeseries day files should fail less often on temporary network issues.

**Comment by heidi-holm-4ss** [comment]
It is the PR title that becomes a part of the release notes, and the label we choose determines what category the PR is listed under. 

For the commit message it is just a guideline so it is easier to understand what has happened when you look at the history

**Pull request merged**
