### PR TITLE
Move Series <-> DataFrame convertion out of Storage and into Client

### PR DESCRIPTION
**Pull request by ace-e4s**
## Description
`storage.Storage` class is further simplified. Now it only deals with transfering dataframes to and from storage (remote + local cache).

Series <-> DataFrame conversion happens in `Client` (`.create` / `.append` /  `.get`).

DataFrames read from remote is assigned "index" and "values" as columns. DataFrame index is just row numbers (default Pandas).

## Checklist
- [x] PR title is descriptive and fit for injection into release notes (see tips below)
- [x] Correct label(s) are used

PR title tips:
* Use imperative mood
* Describe the motivation for change, issue that has been solved or what has been improved - not how
* Examples:
  * Add functionality for Allan variance to sensor_4s.simulate
  * Upgrade to support Python 9.10
  * Remove MacOS from CI

### CODE REVIEW

**Comment by vegard-solum-4ss** [comment]
Got this error when I tried to download some data:

---------------------------------------------------------------------------
IncompleteRead                            Traceback (most recent call last)
Input In [20], in <cell line: 12>()
      9 start_ns = pd.to_datetime(start).value
     10 end_ns = pd.to_datetime(end).value
---> 12 data = client.get(ts_id, start=start, end=end)

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\client.py:292, in Client.get(self, series_id, start, end, convert_date, raise_empty)
    288 time_start = timeit.default_timer()
    290 log.debug("Getting series range")
    291 series = (
--> 292     self._storage.get(series_id, start, end)
    293     .set_index("index")
    294     .squeeze("columns")
    295     .loc[start:end]
    296     .copy(deep=True)
    297 )
    298 series.index.name = None
    300 if series.empty and raise_empty:  # may become empty after slicing

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:89, in Storage.get(self, timeseries_id, start, end)
     87 log.debug("getting day file inventory")
     88 response = self._timeseries_api.download_days(timeseries_id, start, end)
---> 89 df = self._downloader.get(response)
     90 return df

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:110, in BaseDownloader.get(self, response)
    107 filedatas = map(self._download_chunks_as_dataframe, filechunks)
    109 try:
--> 110     df = next(filedatas)
    111 except StopIteration:
    112     return pd.DataFrame()

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:124, in BaseDownloader._download_chunks_as_dataframe(self, chunks)
    122 with ThreadPoolExecutor(max_workers=1) as executor:
    123     filechunks = executor.map(self._download_verified_chunk, chunks)
--> 124 df_chunks = pd.concat(filechunks)
    125 return df_chunks

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\core\reshape\concat.py:368, in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    146 @deprecate_nonkeyword_arguments(version=None, allowed_args=["objs"])
    147 def concat(
    148     objs: Iterable[NDFrame] | Mapping[HashableT, NDFrame],
   (...)
    157     copy: bool = True,
    158 ) -> DataFrame | Series:
    159     """
    160     Concatenate pandas objects along a particular axis.
    161 
   (...)
    366     1   3   4
    367     """
--> 368     op = _Concatenator(
    369         objs,
    370         axis=axis,
    371         ignore_index=ignore_index,
    372         join=join,
    373         keys=keys,
    374         levels=levels,
    375         names=names,
    376         verify_integrity=verify_integrity,
    377         copy=copy,
    378         sort=sort,
    379     )
    381     return op.get_result()

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\core\reshape\concat.py:422, in _Concatenator.__init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    420     objs = [objs[k] for k in keys]
    421 else:
--> 422     objs = list(objs)
    424 if len(objs) == 0:
    425     raise ValueError("No objects to concatenate")

File C:\Program Files\Python39\lib\concurrent\futures\_base.py:609, in Executor.map.<locals>.result_iterator()
    606 while fs:
    607     # Careful not to keep a reference to the popped future
    608     if timeout is None:
--> 609         yield fs.pop().result()
    610     else:
    611         yield fs.pop().result(end_time - time.monotonic())

File C:\Program Files\Python39\lib\concurrent\futures\_base.py:439, in Future.result(self, timeout)
    437     raise CancelledError()
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File C:\Program Files\Python39\lib\concurrent\futures\_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

File C:\Program Files\Python39\lib\concurrent\futures\thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:132, in BaseDownloader._download_verified_chunk(self, chunk)
    127 def _download_verified_chunk(self, chunk):
    128     """
    129     Download chunk as pandas DataFrame and ensure the series does not contain
    130     duplicates.
    131     """
--> 132     df = self._backend.get(chunk)
    133     if not df.index.is_unique:
    134         return df[~df.index.duplicated(keep="last")]

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:277, in FileCacheDownload.get(self, chunk)
    275     log.debug(f"Cache miss on {id_}")
    276     blob_url = chunk["Endpoint"]
--> 277     data = _blob_to_df(blob_url)
    278     self._put_data_to_cache(data, id_, md5)
    279 else:

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\storage\storage.py:399, in _blob_to_df(blob_url)
    383 def _blob_to_df(blob_url):
    384     """
    385     Download blob from remote storage and present as a Pandas Series.
    386 
   (...)
    397         or ``float64``.
    398     """
--> 399     df = pd.read_csv(
    400         blob_url,
    401         header=None,
    402         names=("index", "values"),
    403         dtype={"index": "int64", "values": "str"},
    404         encoding="utf-8",
    405     ).astype({"values": "float64"}, errors="ignore")
    406     return df

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\util\_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\parsers\readers.py:950, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    946     defaults={"delimiter": ","},
    947 )
    948 kwds.update(kwds_defaults)
--> 950 return _read(filepath_or_buffer, kwds)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\parsers\readers.py:605, in _read(filepath_or_buffer, kwds)
    602 _validate_names(kwds.get("names", None))
    604 # Create the parser.
--> 605 parser = TextFileReader(filepath_or_buffer, **kwds)
    607 if chunksize or iterator:
    608     return parser

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\parsers\readers.py:1442, in TextFileReader.__init__(self, f, engine, **kwds)
   1439     self.options["has_index_names"] = kwds["has_index_names"]
   1441 self.handles: IOHandles | None = None
-> 1442 self._engine = self._make_engine(f, self.engine)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\parsers\readers.py:1735, in TextFileReader._make_engine(self, f, engine)
   1733     if "b" not in mode:
   1734         mode += "b"
-> 1735 self.handles = get_handle(
   1736     f,
   1737     mode,
   1738     encoding=self.options.get("encoding", None),
   1739     compression=self.options.get("compression", None),
   1740     memory_map=self.options.get("memory_map", False),
   1741     is_text=is_text,
   1742     errors=self.options.get("encoding_errors", "strict"),
   1743     storage_options=self.options.get("storage_options", None),
   1744 )
   1745 assert self.handles is not None
   1746 f = self.handles.handle

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\common.py:713, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    710     codecs.lookup_error(errors)
    712 # open URLs
--> 713 ioargs = _get_filepath_or_buffer(
    714     path_or_buf,
    715     encoding=encoding,
    716     compression=compression,
    717     mode=mode,
    718     storage_options=storage_options,
    719 )
    721 handle = ioargs.filepath_or_buffer
    722 handles: list[BaseBuffer]

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\io\common.py:368, in _get_filepath_or_buffer(filepath_or_buffer, encoding, compression, mode, storage_options)
    365         if content_encoding == "gzip":
    366             # Override compression based on Content-Encoding header
    367             compression = {"method": "gzip"}
--> 368         reader = BytesIO(req.read())
    369     return IOArgs(
    370         filepath_or_buffer=reader,
    371         encoding=encoding,
   (...)
    374         mode=fsspec_mode,
    375     )
    377 if is_fsspec_url(filepath_or_buffer):

File C:\Program Files\Python39\lib\http\client.py:476, in HTTPResponse.read(self, amt)
    474 else:
    475     try:
--> 476         s = self._safe_read(self.length)
    477     except IncompleteRead:
    478         self._close_conn()

File C:\Program Files\Python39\lib\http\client.py:628, in HTTPResponse._safe_read(self, amt)
    626 chunk = self.fp.read(min(amt, MAXAMOUNT))
    627 if not chunk:
--> 628     raise IncompleteRead(b''.join(s), amt)
    629 s.append(chunk)
    630 amt -= len(chunk)

IncompleteRead: IncompleteRead(35555712 bytes read, 23974 more expected)

**Comment by vegard-solum-4ss** [comment]
> 

Next time I tried to download the same data, it worked

**Comment by vegard-solum-4ss** [comment]
I have not been able to recreate the error. Neither with `cache=True` or `cache=False`.

**Comment by vegard-solum-4ss** [comment]
Also, note that this PR will make the `client.get()` fail if used with old cached data. Then, you will get this error: 


---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [37], in <cell line: 15>()
     12 start_ns = pd.to_datetime(start).value
     13 end_ns = pd.to_datetime(end).value
---> 15 data = client.get(ts_id, start=start, end=end)

File ~\WorkroomDS\GitHub\drio-python\datareservoirio\client.py:292, in Client.get(self, series_id, start, end, convert_date, raise_empty)
    288 time_start = timeit.default_timer()
    290 log.debug("Getting series range")
    291 series = (
--> 292     self._storage.get(series_id, start, end)
    293     .set_index("index")
    294     .squeeze("columns")
    295     .loc[start:end]
    296     .copy(deep=True)
    297 )
    298 series.index.name = None
    300 if series.empty and raise_empty:  # may become empty after slicing

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\util\_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File ~\AppData\Local\Programs\Python\lib\site-packages\pandas\core\frame.py:6009, in DataFrame.set_index(self, keys, drop, append, inplace, verify_integrity)
   6006                 missing.append(col)
   6008 if missing:
-> 6009     raise KeyError(f"None of {missing} are in the columns")
   6011 if inplace:
   6012     frame = self

KeyError: "None of ['index'] are in the columns"

**Comment by vegard-solum-4ss** [comment]
Set `STOREFORMATVERSION = "v3".

**Review by vegard-solum-4ss — DISMISSED** [review]

**Comment by ace-e4s** [comment]
I have made 2 changes/fixes:

1.  Addressing cache conflict with existing cache -> cranked up cache version to "v3". This mean that cache stores to a fresh folder for default.
2. Issue with properly concatinating dfs when downloading several days. Applied a hotfix in BaseDownloader. We will rewrite it anyways, so we can do a more appropriate fix then.

The issue with IncompleteRead must be addressed separately, made a bug user story.

WARNING: the unit-tests are not functioning as intended! They fail when you fix a bug, and not when you introduce one! (The issue with Basedownloader was not caught by tests. However, when I applied the hotfix, some tests failed.)

**Review by vegard-solum-4ss — APPROVED** [review]
Looks good! Tested the caching, seems to work fine now.

**Pull request merged**
